### ISSUE TITLE
key.blend missing

### ISSUE THREAD

**Issue by Muhammad-Jamal** [ThiDiamondDev/inventory-interaction-system#3]
dependency missing issue, the missing it says is key,blend

**Comment by Jonurk** [comment]
These are the errors that I am having when opening the project:
![imagen](https://github.com/user-attachments/assets/77f2ea31-d928-4b12-8910-44f8b85fb22c)

**Comment by ThiDiamondDev** [comment]
Please make sure you have blender installed, and in the Editor Settings, FileSystem/Import/Blender Path is set correctly.
